# Generated by Django 3.1.2 on 2020-10-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('education', models.CharField(max_length=300)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.user')),
            ],
        ),
    ]
