# Generated by Django 3.1.2 on 2020-10-13 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekr', '0002_jobseekerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndustryName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=1000)),
                ('SalaryUp', models.IntegerField()),
                ('SalaryDown', models.IntegerField()),
                ('CompanyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillName', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='jobseekerdetails',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='jobseekerdetails',
            old_name='education',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='jobseekerdetails',
            old_name='userid',
            new_name='UserId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='UserName',
        ),
        migrations.CreateModel(
            name='SubIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubIndustryName', models.CharField(max_length=40)),
                ('IndustryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.industry')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.skills')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.user')),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchStatus', models.CharField(max_length=50)),
                ('JobListingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.joblisting')),
                ('SubIndustryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.subindustry')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.user')),
            ],
        ),
        migrations.CreateModel(
            name='JobListingSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobListingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.joblisting')),
                ('SkillsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.skills')),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='JobTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.jobtype'),
        ),
        migrations.AddField(
            model_name='company',
            name='IndustryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekr.industry'),
        ),
    ]
