# Generated by Django 3.1.2 on 2020-10-13 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seekr', '0003_auto_20201013_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='IndustryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='IndustryName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='CompanyId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.company'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='JobTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seekr.jobtype'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='SalaryDown',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='SalaryUp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblistingskills',
            name='JobListingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.joblisting'),
        ),
        migrations.AlterField(
            model_name='joblistingskills',
            name='SkillsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.skills'),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='JobListingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.joblisting'),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='MatchStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='SubIndustryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.subindustry'),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobseekerdetails',
            name='Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerdetails',
            name='Education',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerdetails',
            name='UserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobseekerskills',
            name='SkillsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.skills'),
        ),
        migrations.AlterField(
            model_name='jobseekerskills',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='TypeName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='SkillName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subindustry',
            name='IndustryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.industry'),
        ),
        migrations.AlterField(
            model_name='subindustry',
            name='SubIndustryName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
