# Generated by Django 3.1.2 on 2020-10-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekr', '0005_auto_20201024_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerdetails',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerdetails',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
