# Generated by Django 3.1.2 on 2020-11-08 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seekr', '0008_jobmatch_percentagematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLPClusters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClusterId', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClusterId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.nlpclusters')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobListingGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClusterId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.nlpclusters')),
                ('JobListingId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekr.joblisting')),
            ],
        ),
    ]
