# Generated by Django 3.1.2 on 2020-11-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekr', '0010_nlpclusters_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nlpclusters',
            name='Size',
        ),
        migrations.AddField(
            model_name='nlpclusters',
            name='NormSize',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True),
        ),
    ]
