# Generated by Django 3.1.2 on 2020-11-08 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seekr', '0011_auto_20201108_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobSeekerGroup',
            new_name='JobSeekerGroups',
        ),
    ]
