# Generated by Django 3.1.2 on 2020-11-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekr', '0012_auto_20201108_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='Longitude',
        ),
        migrations.RemoveField(
            model_name='jobseekerdetails',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='jobseekerdetails',
            name='Longitude',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='City',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='State',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='Street',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='StreetNumber',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='Suburb',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerdetails',
            name='City',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerdetails',
            name='State',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerdetails',
            name='Street',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerdetails',
            name='StreetNumber',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerdetails',
            name='Suburb',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
